### ISSUE TITLE
feature request(s): sort on save

### ISSUE THREAD

**Issue by tehOPEologist** [Debens/sort-js-object#1]
hi there!  this extension is pretty much exactly what i'm looking for to sort my react-native StyleSheet objects, but i'd love to see the addition of sort on save so that i don't have to select the object that needs sorting and hit the hotkey.  i think this is possible for my use-case, because my styles are in their own isolated file (styles.js), which only exports the return of the StyleSheet.create() method.  an example of a file i'd like to use this with is below:

```
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    foo: {
        textAlign: 'center',
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        fontSize: 16,
    },
    bar: {
        textAlign: 'center',
        backgroundColor: '#f00',
    },
});
```

once saved, the extension would auto-sort/save to have the file look like below:

```
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    bar: {
        backgroundColor: '#f00',
        textAlign: 'center',
    },
    foo: {
        alignItems: 'center',
        bottom: 0,
        flexDirection: 'row',
        fontSize: 16,
        left: 0,
        position: 'absolute',
        right: 0,
        textAlign: 'center',
        top: 0,
    },
});
```

i would love to be able to use this extension on these styles.js files only, and be able to have the extension know i'm on this specific filename+extension and to look for the object within the StyleSheet.create() method and run it's sort when i save the file.  i'm not versed in vscode extension creation and your extension has ~ 90% of what i'm looking for, so i'd love to see this get implemented!  i'd be willing to test anything at a moment's notice, since this is something myself and my team are clamoring for!  thanks so much again!

**Comment by Debens** [comment]
Thanks for the suggestion! I gave this some though while putting this together the extension but was worried about how it would contradict other formatters such as prettier. Prettier annoying does not integrate well with custom opinionated formatters so sadly I couldn't get in the integration working.  

This then could end up formatting the same file multiple times on save, and I'm not sure on the order the formatting would run?

This doesn't mean that we couldn't try something like a format on save option which is designed to be overly specific, scoping the formatting to specific files, but it wouldn't be very performant.

I'll give it a look when I get some time, sorry if it isn't in the near future.

**Comment by tehOPEologist** [comment]
no worries, i'm actually ok with just cmd+a, alt+s, cmd+s...  it's not too bad, and there's only a little cleanup from it killing \n's, but overall it does exactly what i was looking for to make alphabetizing react-native StyleSheets super fast, so thank you!  you can close this or document the request somewhere if you'd like, as i'm no longer blocked after getting used to the hotkey :)

**Comment by Debens** [comment]
I added a new hotkey for ya, `ctrl+alt+s`, that will sort a focused file to save you at couple key presses, but the output is not pretty. 

When I put some more time in I can try make the output work on save though using the (registerDocumentFormattingEditProvider)[https://code.visualstudio.com/api/references/vscode-api] and replacing only the specific targeted sub expression trees that can be formatted. (I'm just referencing this for myself when I come back later). Then you would be able to use the default `editor.formatOnSave` vscode option and it would hopefully play much nice with prettier!

For now I'm going to close this ticket though. Feel free to open another if you need more.
