### ISSUE TITLE
Unable to sort highlighted selection, only entire file

### ISSUE THREAD

**Issue by adlondon** [Debens/sort-js-object#6]
First, thanks a ton for creating this extension. Ive been looking for something like it for awhile...

I'm unable to sort the highlighted selection for this object... Even if I place it in it's own file, select the object, and `alt + s` it returns the `Please make sure your selected text is a JS object` error. Only if I sort the entire file with `ctrl + alt + s` does it sort properly. The object is similar to this: 

```
const myObject = {
  foo: (bar) => ({
    ...bar,
    a: true,
  }),
  bazz: (buzz) => ({
    ...buzz,
    b: false,
  })
}
```

Any insight would be greatly appreciated

**Comment by Debens** [comment]
![sorting](https://user-images.githubusercontent.com/25802264/93061626-bb263b80-f66b-11ea-8d9d-cb2463286036.gif

 I'm afraid I cannot reproduce this issue

**Comment by Debens** [comment]
Closing as stale
